### 1. login user
POST http://localhost:5027/Calender-Website/login-user HTTP/1.1
content-type: application/json

{
    "Email": "Mail.com",
    "Password": "Password"
}

### 2. attend attendance to office
POST http://localhost:5027/Calender-Website/attend HTTP/1.1
content-type: application/json

{
  "Date": "2024-10-29 08:00"
}

### 3. check own attendances
Get http://localhost:5027/Calender-Website/check-own-attendances HTTP/1.1

### 4. logout user
POST http://localhost:5027/Calender-Website/logout HTTP/1.1

### 5. login user
POST http://localhost:5027/Calender-Website/login-user HTTP/1.1
Content-Type: application/json

{
    "Email": "testemail.com",
    "Password": "testpassword"
}

### 6. attend attendance to office
POST http://localhost:5027/Calender-Website/attend HTTP/1.1
Content-Type: application/json

{
  "Date": "2024-10-10 08:00"
}

### 7. check own attendances
Get http://localhost:5027/Calender-Website/check-own-attendances HTTP/1.1

### 8. logout user
POST http://localhost:5027/Calender-Website/logout HTTP/1.1
