### 1. login admin
POST http://localhost:5027/Calender-Website/login-admin HTTP/1.1
content-type: application/json

{
  "Username": "TestUsername",
  "Password": "TestPassword"
}

#Create Event
POST http://localhost:5027/Calender-Website/create-event HTTP/1.1
content-type: application/json
{
    "Title": "Annual Conference",
    "Description": "This is a detailed description of the event.",
    "Date": "2024-12-25T00:00:00",
    "StartTime": "2024-12-25T09:00:00",
    "EndTime": "2024-12-25T17:00:00",
    "Location": "Convention Center, City",
    "AdminApproval": false
}

#Get Event
GET http://localhost:5027/Calender-Website/event?id=a8ad48c9-aee8-495b-b86a-6be42874b6fd

#Delete Event
DELETE http://localhost:5027/Calender-Website/delete-event?id=a8ad48c9-aee8-495b-b86a-6be42874b6fd


#Create Event (For Update)
POST http://localhost:5027/Calender-Website/create-event HTTP/1.1
content-type: application/json
{
    "Title": "Annual Conference",
    "Description": "This is a detailed description of the event.",
    "Date": "2024-12-25T00:00:00",
    "StartTime": "2024-12-25T09:00:00",
    "EndTime": "2024-12-25T17:00:00",
    "Location": "Convention Center, City",
    "AdminApproval": false
}

#Update Event
PUT http://localhost:5027/Calender-Website/update-event?id=a8ad48c9-aee8-495b-b86a-6be42874b6fd HTTP/1.1
content-type: application/json
{
    "Title": "Weekly Conference",
    "Description": "This is a detailed description of the event.",
    "Date": "2024-12-25T00:00:00",
    "StartTime": "2024-12-25T09:00:00",
    "EndTime": "2024-12-25T17:00:00",
    "Location": "Convention Center, City",
    "AdminApproval": false
}

#Post Review
POST http://localhost:5027/Calender-Website/review HTTP/1.1
content-type: application/json
{
  "EventId" : "a8ad48c9-aee8-495b-b86a-6be42874b6fd",
  "Rating" : 5.0,
  "Feedback" : "Pretty good."
}

#Get Reviews of Event
GET http://localhost:5027/Calender-Website/review?id=a8ad48c9-aee8-495b-b86a-6be42874b6fd

#Add Extra Event

POST http://localhost:5027/Calender-Website/create-event HTTP/1.1
content-type: application/json
{
    "Title": "Annual Conference",
    "Description": "This is a detailed description of the event.",
    "Date": "2024-12-25T00:00:00",
    "StartTime": "2024-12-25T09:00:00",
    "EndTime": "2024-12-25T17:00:00",
    "Location": "Convention Center, City",
    "AdminApproval": false
  }

#Get all Events
GET http://localhost:5027/Calender-Website/get-all-events